name: Placeholder CI

on:
  pull_request:
    branches:
      - main  # ou a branch principal do seu repositório

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Placeholder de build
        run: echo "Tudo certo!"
