name: Deploy Azure Function

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend
          pip install -r requirements.txt

      - name: Azure Functions Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: restaurant-gpt
          package: ./Backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
