name: Build and deploy Python project to Azure Function App - restaurant-gpt

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Backend'
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      - name: Zip artifact
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../function.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0481E5BE40F346F8A3ED75193024AFDB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49839D7B608445E3BD41AE00F2D8944E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_433575CC698B44DDAD062F23003631E4 }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --name restaurant-gpt \
            --resource-group Restaurant-GPT \
            --src function.zip \
            --build-remote true

